"""Add user id and blog id FK to Comment table

Revision ID: 7362b1155cfb
Revises: 1f433b136609
Create Date: 2024-01-16 12:39:41.780468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7362b1155cfb'
down_revision = '1f433b136609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('blog_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_comments_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_comments_blog_id_blogs'), 'blogs', ['blog_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comments_blog_id_blogs'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comments_user_id_users'), type_='foreignkey')
        batch_op.drop_column('blog_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
